export default {
  AUTH_DATA: 'AUTH_DATA',
  AUTH_LOADER: 'AUTH_LOADER',
  WORKBOOKS: 'WORKBOOKS',
  WORKBOOKS_LOADER: 'WORKBOOKS_LOADER',
  SELECT_WORKBOOK: 'SELECT_WORKBOOK',
  WORKBOOK_VIEWS: 'WORKBOOK_VIEWS',
  ADD_WORKBOOK_FILTERS: 'ADD_WORKBOOK_FILTERS',
  DELETE_WORKBOOK_FILTERS: 'DELETE_WORKBOOK_FILTERS',
};
